auctionwebsite/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static # < this

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('user_app.urls',namespace='users')),
    # path('accounts/', include('user_app.urls',namespace='accounts')),
    path('',include('goods_app.urls',namespace='goods')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # < this

goods_app/urls.py
from django.urls import path
from .views import (IndexView,
                    AboutView,
                    ContactView,
                    GoodsView,
                    GoodsDetails,
                    AjaxGetInfoView,goods_create_view)
# from user_app.views import UploadView

app_name='goods_app'

urlpatterns = [
    
    path('goods/',GoodsView.as_view(),name='empty'),
    path('contact/',ContactView.as_view(),name='contact'),
    path('about/',AboutView.as_view(),name='about'),
    path('',IndexView.as_view(),name='goods'),
    # path('categories/<pk>/',GoodsCategories.as_view(),name='categories'),
    path('goods/<int:pk>/',GoodsDetails.as_view(),name='detail'),
    path('ajax/<int:pk>/',AjaxGetInfoView,name='ajax-detail'),
    path('upload/',goods_create_view, name='upload'),

]

user_app/urls.py
from django.urls import path
from .views import SignUpView, CustomLoginView,SettingsView,ContactMessageView,UserProfilUpdateView#,UserProfilView
from django.contrib.auth.views import LoginView,LogoutView
app_name='user_app'
urlpatterns = [
    path('register/',SignUpView.as_view(),name='register'),
    path('login/',CustomLoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view() ,name="logout"),
    path('user-profile/',UserProfilUpdateView,name="profile"),
    path('send-message/',ContactMessageView.as_view() ,name="send-message"),
    path('change-password/',SettingsView.as_view() ,name="change-password"),
    # path('update/', UserProfilUpdateView,name='update')
    #      name='user-detail'),
    
]

goods_app/models.py
from django.db import models
from user_app.models import MyUser
from django.contrib.auth.models import User
from easy_thumbnails.fields import ThumbnailerImageField

# Create your models here.
class Goods(models.Model):
    name=models.CharField(max_length=255)
    price=models.IntegerField()
    photo = models.ImageField(upload_to='photos', blank=True)
    description=models.CharField(max_length=255)
    
    
    class Meta:
        verbose_name='Goods'
        verbose_name_plural='Goods'

    def __str__(self):
        return self.name



    

goods_app/forms.py
from django import forms
from .models import Goods
class GoodsUploadForm(forms.ModelForm):
    class Meta:
        model=Goods
        fields=['name','price','photo','description']

goods_app/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView,DetailView,TemplateView,UpdateView
from django.http import JsonResponse
from django.urls import reverse_lazy
from time import strftime
from .models import Goods
from .forms import GoodsUploadForm
from user_app.views import MyUser



def goods_create_view(request):
    if request.method == 'POST':
        print("Yuklenen fayl: ",request.FILES)
        form=GoodsUploadForm(request.POST,request.FILES)
       
        if form.is_valid():
            goods = form.save(commit=False)
            goods.owner = request.user
            goods.save()
            return render(request,'user_profile.html')

    return redirect(reverse_lazy('users:user-detail',  kwargs={'pk': request.user.id}))

class AboutView(TemplateView):
    template_name='about.html'
    
class IndexView(TemplateView):
    template_name='main.html'
   
class ContactView(TemplateView):
    template_name='contact.html'
    
    


class RaiseView(UpdateView):
    model = Goods
    fields = ['price']
    success_url=reverse_lazy('goods:goods')
    def post(self, request, *args, **kwargs):
        price=Goods.objects.get(id=kwargs['pk']).price
        my_user = MyUser.objects.get(user=request.user.id)
        budget=my_user.budget

        # before_person=Goods.objects.get(id=kwargs['pk'])
        # print(my_user)
        # print(before_person)
        offer=int(request.POST['price'])
        if offer>price and offer<=budget:
            good = self.get_object()
            son_teklif_eden_id=good.offer_person.user.id
            aktiv_id=request.user.id
           
            if son_teklif_eden_id==aktiv_id:
                data={'error':'Hal-hazırda ən yüksək təklif sizindir'}
                return JsonResponse(data=data)
            
            good.offer_person.budget+=price
            good.offer_person.save()
            my_user.budget-=offer
            my_user.save()
            # print(my_user.budget)

            # my_user.budget+=price
            # print(my_user.budget)
            super().post(request, *args, **kwargs)
            good.offer_person = my_user
            good.price  = offer
            good.save()
            data={'price':offer}
            # print(kwargs)
            # person=Goods.objects.get(id=kwargs['pk'])
            # print(person)


          
        elif offer>budget:
            data={'error':'Kifayət qədər pulunuz yoxdur...'}
           
        elif offer<=price:
            data={'error':'Təklif etdiyiniz məbləğ daha yüksək olmalıdır...'}
        else:
            data={'error':'Bilinməyən bir xəta baş verdi...'}
        return JsonResponse(data=data)
def AjaxGetInfoView(request,pk):
    if request.method == 'POST':
        obj=Goods.objects.get(id=pk)
     
        return JsonResponse(data={'obj':obj.price})

class GoodsDetails(DetailView):
    model=Goods
    context_object_name='goods'
    template_name='detailed.html'

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     good = self.get_object()
    #     zaman=good.auctionDeadLine
    #     convert=zaman.strftime('%d %b %Y').upper()+ " " +zaman.strftime('%H:%M:%S')
    #     context["deadline"] = convert
    #     return context

# class GoodsCategories(ListView):
#     model=Goods
#     context_object_name='goods'
#     template_name='goods_categories.html'
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context["categories"] = Category.objects.all()
#         return context
        
#     def get_queryset(self,**kwargs):

#         #print(self.kwargs)
#         return Goods.objects.filter(category=self.kwargs['pk'])
class GoodsView(ListView):
    model=Goods
    context_object_name='goods'
    template_name='store.html'
    paginate_by=6
    
    def get_queryset(self):
        sorgu = self.request.GET.get('word')
        if type(sorgu).__name__ == 'NoneType':
            return Goods.objects.all()
        else:
            return Goods.objects.filter(name__icontains=sorgu)

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context["categories"] = Category.objects.all()
    #     return context
# class SearchView(ListView):
#     model=Goods
#     context_object_name='goods'
#     template_name='search_list.html'
#     def get_queryset(self,**kwargs):
#         query=self.request.GET.get('q')
#         print(query)
#         if query:
#             print(Goods.objects.filter(name=query))
#             return Goods.objects.filter(name=query)
#         else:
#             return Goods.objects.all()

goods_app/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid p-0 m-0">
    {% include 'navbar.html' %} 
    <!-- SLIDE -->
    <div id="carouselExampleControls"  class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'image/main_slide/image_1.jpg' %}" class="d-block w-100" >
            </div>
            <div class="carousel-item">
                <img src="{% static 'image/main_slide/image_2.jpg' %}" class="d-block w-100" >
            </div>
            <div class="carousel-item">
                <img src="{% static 'image/main_slide/image_3.jpg' %}" class="d-block w-100" >
            </div>
        </div>
        <!-- SEARCH BURADA -->
        <div class="row" id="title" >
            <div  class="col-md-12"> 
                <h2 class="slide_h2">MADE WITH LOVE AND  PASSION</h2>
                <p class="slide_p">MAKE YOUR BID AND GET THE BEST HANDMADE GOODS EVER</p>
                <button class="get_started">GET STARTED</button>
            </div>
        </div>
    </div>  
</div>
     <!-- COMPANY HISTORY -->
<div class="container">
    <div class="row company_history">
        <div class="container">
            <div class="row justify-content-center ">
                 <div class="col-md-5  ">
                     <h3>Company History</h3>
                     <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Officia, voluptate! Numquam error possimus ratione reiciendis minima voluptatem saepe ab minus et.amet consectetur adipisicing elit. Officia, voluptate! Numquam error possimus ratione reiciendis minima voluptatem saepe ab minus etamet consectetur adipisicing elit. Officia, voluptate! Numquam error possimus ratione reiciendis minima voluptatem saepe ab minus et Soluta ipsa consequuntur saepe eum omnis, enim placeat? Quibusdam sequi quaerat blanditiis aliquam esse aliquid tempora .</p>
             
                 </div>
                 <div class="col-md-5">
                     <img id="comphistoryimg" src="{% static 'image/main_slide/image_1.jpg' %}" alt="">
                 </div>
             
            </div>
        </div>
     
     </div>
     <!-- TEAM MEMBERS -->
     
     <div  class="row" id="teamtitle">
         <div class="col-md-12 p-0 text-center">
        
             <h3>Team Members</h3>
         </div>
     
     </div>
     
     <div class="row team">
         <div class="col-md-4 komanda">
             <div class="card middle">
                 <div class="front">
                     <img src="{% static 'image/workpic/rashid.jpg' %}" alt="">
                 </div>
                 <div class="back">
                     <div class="back-content middle">
                         <h2>Rashid Jabrayil</h2>
                         <span>Front-End Developer</span>
                         <div class="sm">
                             <a href="#"><i class="fa fa-facebook-f"></i></a>
                             <a href="#"><i class="fa fa-twitter"></i></a>
                             <a href="#"><i class="fa fa-youtube"></i></a>
                             <a href="#"><i class="fa fa-instagram"></i></a>
                         </div>
                     </div>
                 </div>
             </div>
         </div>
     
         <div class="col-md-4 komanda">
             <div class="card middle">
                 <div class="front">
                     <img src="{% static 'image/workpic/ali.jpg' %}" alt="">
                 </div>
                 <div class="back">
                     <div class="back-content middle">
                        <h2>Ali Hasanov</h2>
                        <span>Back-End Developer </span>
                        <div class="sm">
                            <a href="https://www.facebook.com/cinarli057/" target="_blank">
                                <i class="fa fa-facebook-f"></i>
                            </a>
                           <a href="https://twitter.com/cinarli57" target="_blank">
                                <i class="fa fa-twitter"></i>
                            </a>
                             <a href="https://www.youtube.com/channel/UC2UoCvBoqXPEiCIbDNN6tog?view_as=subscriber" target="_blank">
                               <i class="fa fa-youtube"></i>
                            </a>
                            <a href="https://www.instagram.com/cinarli57/" target="_blank">
                                <i class="fa fa-instagram"></i>
                            </a>
                        </div>
                     </div>
                 </div>
             </div>
         </div>
         
     
         <div class="col-md-4 komanda">
             <div class="card middle">
                 <div class="front">
                     <img src="{% static 'image/workpic/idris.jpg' %}" alt="">
                 </div>
                 <div class="back">
                     <div class="back-content middle">
                     <h2>Idris Shabanli</h2>
                     <span> Super Back-End Developer</span>
                     <div class="sm">
                         <a href="#"><i class="fa fa-facebook-f"></i></a>
                         <a href="#"><i class="fa fa-twitter"></i></a>
                         <a href="#"><i class="fa fa-youtube"></i></a>
                         <a href="#"><i class="fa fa-instagram"></i></a>
                     </div>
                     </div>
                 </div>
             </div>
         </div>
     </div>
     {% include 'footer.html' %} 
</div>
         
{% endblock content %} 

goods_app/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div class="container-fluid p-0 m-0">
      {% include 'navbar.html' %} 
        <!-- SLIDE -->
       <div id="carouselExampleControls"  class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="{% static 'image/main_slide/image_1.jpg' %}" class="d-block w-100" >
                </div>
                <div class="carousel-item">
                    <img src="{% static 'image/main_slide/image_2.jpg' %}" class="d-block w-100" >
                </div>
                <div class="carousel-item">
                    <img src="{% static 'image/main_slide/image_3.jpg' %}" class="d-block w-100" >
                </div>
            </div>
          <!-- SEARCH BURADA -->
            <div class="row" id="title" >
                <div  class="col-md-12"> 
                        <h2 class="slide_h2">MADE WITH LOVE AND  PASSION</h2>
                        <p class="slide_p">MAKE YOUR BID AND GET THE BEST HANDMADE GOODS EVER</p>
                        <button class="get_started">GET STARTED</button>
                </div>
            </div>
       </div>  
    </div>

<div class='container'>

<!-- ADRESS PHONE MAIL -->

    <div class="row justify-content-center container_info">
        <div class="col-md-10">   
            <div class="row">
                <div class="col-md-4 contact_p">
                        <!-- <i class="fa fa-map-marker-alt"></i>        -->
                    <!-- <i class="fa fa-map-marker-alt"></i> iconlari tap duzelt -->
                    <p><i class="fa fa-map-marker"></i>&nbsp &nbsp  89 Ataturk avenue, Baku</p>
                </div>
            
        
                <div class="col-md-4 contact_p">
                    <p><i class="fa fa-phone"></i>&nbsp &nbsp+994 70 930 94 36 </p>
                </div>
            
            
                <div class="col-md-4 contact_p">
                    <p><i class="fa fa-envelope"></i>&nbsp &nbspmadewithlove@gmail.com</p>
                </div>
            </div>
        </div>
    </div>
       
    <!-- 
    CONTACT FORM -->
    
    <div class="row justify-content-center getintouchrow">
        
        <div class="col-md-10 box">
            <!-- <div class=""> -->
                <form action='{% url "users:send-message" %}' id="contactForm" method='POST'>
                {% csrf_token %}
                    <h2 id="getin">Get in touch with us</h2>
                    <input type="text" name="name" value="{{user.first_name}}" class="form-control inp" placeholder="Enter Your Name" id="name" required>
                    <input type="email" name="email" value="{{user.email}}" id="email" class="form-control inp" placeholder="Enter Your Email" required>
                    <textarea name="message" id="message" class="form-control inp" placeholder="Message" rows="4" required></textarea>
                    <input type="submit" id='send_message_button' class="form-control-submit" value="SEND MESSAGE">
                    <div id="result"></div>
                </form>
            <!-- </div> -->
        </div>
     
    </div>
    
    {% include 'footer.html' %} 

  </div> <!-- SLIDE and title -->
 
   {% endblock content %}   
   {% block scripts %}
   <script>
    // var token = '{{csrf_token}}';

    $("#contactForm").submit(function (e) {
        e.preventDefault()
        var form = $(this);
        var data=form.serialize()
        // console.log(data)
        $.ajax({
            url: $(form).attr("action"),
            type : $(form).attr("method"),
            data: $(form).serialize(),
            beforeSend: function() {
                $(form).find(":input").attr("disabled", true);
                setTimeout(function(){
                    $(form).find(":input").attr("disabled", false);
                    $('#result').html('')
                },3000
                )
            },
            success: function (data) {
                $('#result').append('<div class="alert alert-success" role="alert">Mesajınız göndərildi...</div>')
                
            },
            error: function (request, status, error) {
                $('#result').append('<div class="alert alert-danger" role="alert">Mesajınız göndərilmədi...</div>')
                
            }
        });
    });
  </script>
   {% endblock scripts %}

    


   

goods_app/templates/goods_categories.html
{% extends 'base.html' %}
{% load thumbnail %}
    {% block 'content' %}
    <div class='container-fluid bodyFluid'>
    <div class="row bodyrow">
        {% include 'categories.html' %}
        <div class="col-md-9">

            {% for single_goods in goods %}

            <div class="card" style="width: 18rem;">
            <img class='goodsimg' src="{{single_goods.photo|thumbnail_url:'avatar'}}" class="card-img-top" alt="...">
                {% comment %} <img class='goodsimg' src="{{single_goods.pictures}}" class="card-img-top" alt="..."> {% endcomment %}
                <div class="card-body">
                    <h5 class="card-title">{{single_goods.name}}</h5>
                    <p class="card-text">{{single_goods.description}}</p>
                   
                    <p class="card-text">Price: {{single_goods.price}}</p>
                    <p class="card-text">DeadLine: {{single_goods.auctionDeadLine}}</p>
                     <a href="{% url 'goods:detail' single_goods.pk %}" class="btn btn-primary btn-block">Daha etrafli</a>
                </div>
            </div>
            {% endfor %}



        </div>
            
    </div>
    </div>
    {% endblock 'content' %}
    
        

goods_app/templates/goods_detailed.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}
    {% block content %}
    <div class='container-fluid'>
        <div class="row">
            <div class="col-md-12 path">
                <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'goods:empty' %}">Category</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Data</li>
                </ol>
                </nav>
            </div>
        </div>
    <div class="row content">
        <div class="col-md-6">
               

            <img src="{{goods.photo|thumbnail_url:'avatar_info'}}" width="100%" height="400" alt="">
        </div>
        <div class="col-md-6">
            <h2>{{goods.name}}</h2>
            <p>Hazırkı qiyməti : {{goods.price}} $</p>

            <form action="{% url 'goods:raise' goods.id %}" method="POST">
                {% csrf_token %}
                <input type="text" name='price' placeholder="təklif et">
                <input type="submit" value='Teklif et'>
            </form>

            <p>Size: {{goods.size}}</p>
            <p>Color: {{goods.color}}</p>
            <p>Description: {{goods.description}}</p>
            <p>Owner: {{goods.owner.username}}</p>
            <p>Category: {{goods.category.name}}</p>
            <p>DeadLine: <span id='Deadline'> {{deadline}}</span></p>

            <p>Countdown: 
                <span id='countdown'></span>
            </p>

            {% comment %} <p>Db vaxti: {{dir(dbtime)}}</p> {% endcomment %}
        </div>
    </div>
    </div>
   
    <!-- <div id="getting-started"></div> -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
			  crossorigin="anonymous"></script>
         {% comment %} <script src="{% static 'assets/js/timer.js' %}"></script> {% endcomment %}
    
        <script type="text/javascript">
       
        {% comment %} $('#getting-started').countdown('2020/01/01', function(event) {
            $(this).html(event.strftime('%w weeks %d days %H:%M:%S'));
        }); {% endcomment %}


        //COUNT DOWN begin
   {% comment %} var countDownDate=new Date('30 OCT 2019 00:00:00 GMT').getTime();
   console.log(countDownDate) {% endcomment %}
        {% comment %} var d = Date.parse("30 OCT 2019 00:00:00 GMT"); {% endcomment %}
        var d = Date.parse("{{goods.auctionDeadLine|date:'d m Y h:m:s'}}");
        var x = setInterval(function() {
        var now = new Date().getTime();
                
        // Find the distance between now and the count down date    
        //var distance = countDownDate - now;
        // '30 OCT 2019 00:00:00 GMT'
        // 1571844124596
        
        var countDownDate=new Date('{{deadline}}').getTime();       
        var distance=countDownDate-now
        console.log(distance)
        // console.log(distance)
        // Time calculations for days, hours, minutes and seconds
        var days = Math.floor(distance / (1000 * 60 * 60 * 24));
        var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
        var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
        var seconds = Math.floor((distance % (1000 * 60)) / 1000);
          
        // Output the result in an element with id="demo"
        if (distance < 0) {
          clearInterval(x);
           document.getElementById("countdown").innerHTML ='Time over'
        }
        else if(distance<60000)
            document.getElementById("countdown").innerHTML =seconds+' s'

        else if(distance<3600000)
            document.getElementById("countdown").innerHTML =minutes+' m '+seconds+' s'

        else if(distance<86400000)
            document.getElementById("countdown").innerHTML =hours+' h '+minutes+' m '+seconds+' s'   

        else
            document.getElementById("countdown").innerHTML =days+' d '+hours+' h '+minutes+' m '+seconds+' s'
        // If the count down is over, write some text 
        
      }, 1)
       // Get today's date and time

       


    {% comment %} timedate = $('#timecatcher').attr('data-time')
    var countDownDate = timedate {% endcomment %}

        </script>
    {% endblock content %}
    

goods_app/templates/goods_upload.html
{% extends 'base.html' %}
    {% block content %}
    <div class='container'>
        <div class='row'>
            <div class='col-md-12'>
                <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                    <h2>Your info</h2>
                    <hr>
                    {{form.as_p}}
                    
                    <h2>Good info</h2>
                    <hr>
                    {{my_form.as_p}}
                    

                    <input type="submit" class='btn btn-block btn-info' value="Upload">
                </form>
            
            </div>
        
        </div>
    
    </div>
    
    
      {% endblock content %}

goods_app/templates/index.html
 {% extends 'base.html' %}
    
   
    {% block content %}
    <!-- The content of your page would go here. -->
    <div class="content">index</div>
    {% endblock content %}
    
   

goods_app/templates/search_list.html
{% extends 'base.html' %}
{% load thumbnail %}
    {% block content %}
    <div class='container-fluid bodyFluid'>
    <div class="row bodyrow">
            <div class="col-md-12">
                {% for single_goods in goods %}

                <div class="card" style="width: 18rem;">
                <img class='goodsimg' src="{{single_goods.photo|thumbnail_url:'avatar'}}" class="card-img-top" alt="...">
                    {% comment %} <img class='goodsimg' src="media/{{single_goods.photo}}" class="card-img-top" alt="..."> {% endcomment %}
                    <div class="card-body">
                        <h5 class="card-title">{{single_goods.name}}</h5>
                        <p class="card-text">{{single_goods.description}}</p>
                    
                        <p class="card-text">Price: {{single_goods.price}}</p>
                        <p class="card-text">DeadLine: {{single_goods.auctionDeadLine}}</p>
                        <a href="{% url 'goods:detail' single_goods.pk %}" class="btn btn-primary btn-block">Daha etrafli</a>
                    </div>
                </div>
                {% endfor %} 
            </div>
        
            <div id="container">
                {% if is_paginated %}
                    <div class="pagination dark page_center">

                        {% if page_obj.has_previous %}
                            <a href="?page=1" class="page dark">&laquo; first</a>
                            <a href="?page={{page_obj.previous_page_number}}" class="page dark">&lsaquo; previous</a>
                        {% endif %}

                        {% for num in page_obj.paginator.page_range %}
                                {% if page_obj.number == num  %}
                                    <a href="?page={{ num }}" class="page dark active">{{ num }}</a>

                                {% else %}
                                    <a href="?page={{ num }}" class="page dark">{{ num }}</a>
                                {% endif %}
                        {% endfor %}

                        {% if page_obj.has_next %}
                            <a href="?page={{page_obj.next_page_number}}" class="page dark">next &rsaquo;</a>
                            <a href="?page={{page_obj.paginator.num_pages}}" class="page dark">last &raquo;</a>
                        {% endif %}
                        
                    {% endif %}
                    </div>
                </div>
            </div>
            
    </div>
    </div>
    {% endblock content %}
    
    
        

goods_app/templates/store.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}
{% block content %}
  <div class="container-fluid p-0 m-0">
      {% include 'navbar.html' %} 
        <!-- SLIDE -->
      <div id="carouselExampleControls"  class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="{% static 'image/main_slide/image_1.jpg' %}" class="d-block w-100" >
                </div>
                <div class="carousel-item">
                    <img src="{% static 'image/main_slide/image_2.jpg' %}" class="d-block w-100" >
                </div>
                <div class="carousel-item">
                    <img src="{% static 'image/main_slide/image_3.jpg' %}" class="d-block w-100" >
                </div>
            </div>
          <!-- SEARCH BURADA -->
            <div id="title" class="row">

                <div class="col-md-1"></div>
                <div  class="col-md-10"> 
                      <h2 class="slide_h2">Store</h2>
                      <form action='' method='GET'>
                        <input id="search" name='word' type="text" placeholder="Search">
                        {% comment %} <input href="#" type='submit' value='Axtar' class="search_link"> {% endcomment %}
                        <button id='search_btn' type='submit'><i  class="fa fa-search"></i></button>
                      
                      </form>
                </div>
                <div class="col-md-1"></div>
            
            </div>
      </div>  
  </div>
  <div  class="container">
    <!-- store -->
      <div class="row store">
          <div id="storehead" class="col-md-12"><h3>Store</h3></div>
              {% for single_goods in goods  %}
                  <div class="col-md-6 col-lg-4 goods">
                      <div class="card mx-auto" style="width: 18rem;">
                            <img src="{{single_goods.photo|thumbnail_url:'avatar'}}" class="card-img-top" alt="...">
                            <div class="card-body">
                                <h5 class="card-title">{{single_goods.name}}</h5>
                                <p class="card-text"> {{single_goods.description}}</p>
                               
                                <a href="{% url 'goods:detail' single_goods.pk %}" class="btn btn-primary btn-block">Make a bid</a>
                                <p class="qiymet">$ {{single_goods.price}}</p>
                            </div>
                      </div>
                       
                  </div>
              {% endfor %}
      </div>
      <div class="row justify-content-center">
          <div class="col-md-6">
              {% if is_paginated %}
                  <div class="pagination dark page_center">
                      <div class="pag_all">
                            {% if page_obj.has_previous %}
                            <a href="?page=1" class="page dark">&laquo; first</a>
                            <a href="?page={{page_obj.previous_page_number}}" class="page dark">&lsaquo; previous</a>
                            {% endif %}
    
                            {% for num in page_obj.paginator.page_range %}
                            {% if page_obj.number == num  %}
                                <a href="?page={{ num }}" class="page dark active">{{ num }}</a>
    
                            {% else %}
                                <a href="?page={{ num }}" class="page dark">{{ num }}</a>
                            {% endif %}
                            {% endfor %}
    
                            {% if page_obj.has_next %}
                                <a href="?page={{page_obj.next_page_number}}" class="page dark">next &rsaquo;</a>
                                <a href="?page={{page_obj.paginator.num_pages}}" class="page dark">last &raquo;</a>
                            {% endif %}
                      </div>
                      
                 
                  </div>
                {% endif %}
          </div>
      </div>
  </div>
  <!-- footer -->
  <div class="container-fluid">
    {% include 'footer.html' %}
  </div>
{% endblock content %}
 {% block scripts %}
<script>
     $('#search').change(function() {
        $( "#search_btn" ).trigger( "click" );
});
</script>
 {% endblock scripts %}