auctionwebsite/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static # < this

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('user_app.urls',namespace='users')),
    # path('accounts/', include('user_app.urls',namespace='accounts')),
    path('',include('goods_app.urls',namespace='goods')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # < this

goods_app/urls.py
from django.urls import path
from .views import (IndexView,
                    AboutView,
                    ContactView,
                    GoodsView,
                    GoodsDetails,
                    AjaxGetInfoView,goods_create_view)
# from user_app.views import UploadView

app_name='goods_app'

urlpatterns = [
    
    path('goods/',GoodsView.as_view(),name='empty'),
    path('contact/',ContactView.as_view(),name='contact'),
    path('about/',AboutView.as_view(),name='about'),
    path('',IndexView.as_view(),name='goods'),
    # path('categories/<pk>/',GoodsCategories.as_view(),name='categories'),
    path('goods/<int:pk>/',GoodsDetails.as_view(),name='detail'),
    path('ajax/<int:pk>/',AjaxGetInfoView,name='ajax-detail'),
    path('upload/',goods_create_view, name='upload'),

]

user_app/urls.py
from django.urls import path
from .views import SignUpView, CustomLoginView,SettingsView,ContactMessageView,UserProfilUpdateView#,UserProfilView
from django.contrib.auth.views import LoginView,LogoutView
app_name='user_app'
urlpatterns = [
    path('register/',SignUpView.as_view(),name='register'),
    path('login/',CustomLoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view() ,name="logout"),
    path('user-profile/',UserProfilUpdateView,name="profile"),
    path('send-message/',ContactMessageView.as_view() ,name="send-message"),
    path('change-password/',SettingsView.as_view() ,name="change-password"),
    # path('update/', UserProfilUpdateView,name='update')
    #      name='user-detail'),
    
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Store</title>
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC&display=swap" rel="stylesheet"> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'assets/css/mainstyle.css' %}">
</head>
<body>

{% block content %}
{% endblock content %}

{% comment %} <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> {% endcomment %}
 <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
 {% block scripts %}
 {% endblock scripts %}
<script>
        //sertlerle raziliq
    $('#exampleCheck1').click(function(){
        $("#savesubmitbtn").prop('disabled',!$(this).prop('checked'))
          
    })
    //form send
    $("#signUpForm").submit(function(e){
        e.preventDefault()
        var form = $(this);
        // console.log(data)
         $.ajax({
            url: $(form).attr("action"),
            type : $(form).attr("method"),
            data: $(form).serialize(),
            success: function (data) {
                $('#close_icon_signup').trigger('click')
                $('#login_popup').trigger('click')
                
            },
            error: function (request, status, error) {
                var errorMessage = request.status + ': ' + request.statusText
                
                console.log(errorMessage)
                // $('#result').append('<div class="alert alert-danger" role="alert">Mesajınız göndərilmədi...</div>')
            }
        });
    })
    //login Form
    $("#loginForm").submit(function(e){
        e.preventDefault()
        var form2 = $(this);
        // console.log(data)
         $.ajax({
            url: $(form2).attr("action"),
            type : $(form2).attr("method"),
            data: $(form2).serialize(),
            success: function (data) {
                if(data.is_error){
                    $('#LoginInfo').css('display','inline-block')
                    $('#LoginInfo').html(data.is_error)
                    setTimeout(function(){
                        $('#LoginInfo').hide()
                    },3000)
                }
                else if(data.is_success)
                {
                    window.location = "http://127.0.0.1:8000/"
                }
                // alert(data.is_error)
                // alert(data.is_success)
                
                //alert('oldu'+data.info)
            },
            error: function (request, status, error) {
                var errorMessage2 = request.status + ': ' + request.statusText
                
                alert(errorMessage2)
                // $('#result').append('<div class="alert alert-danger" role="alert">Mesajınız göndərilmədi...</div>')
                
            }
        });
    })
    $('#raise_form').submit(function(e){
        e.preventDefault()
        var form3 = $(this);
        $.ajax({
            url: $(form3).attr("action"),
            type : $(form3).attr("method"),
            data: $(form3).serialize(),
            success: function (data) {
                $('#raise_info').css('display','inline-block')
                if (data.price){
                    $('#raise_info').removeClass('alert-danger')
                    $('.detprice').html(' USD $ '+data.price)
                    $('#raise_info').addClass('alert-success')
                    
                    $('#raise_info').html('Təklif verildi')
                }
                else if(data.error){
                    $('#raise_info').removeClass('alert-success')
                    $('#raise_info').addClass('alert-danger')
                    $('#raise_info').html(data.error)
                }
                
                // setTimeout(function(){
                //     $('#raise_info').hide()
                // },1000)
            },
            error: function (request, status, error) {
                $('#raise_info').addClass('alert-danger')
                $('#raise_info').css('display','inline-block')
                $('#raise_info').html('Səhv baş verdi')
                
                // $('#result').append('<div class="alert alert-danger" role="alert">Mesajınız göndərilmədi...</div>')
                
            }
        });
    })
</script>
</body>
</html>

templates/categories.html
{% load static %}
<div class="col-md-3">
                <ul class="list-group categoryul">
                    <li class="list-group-item categoryli"> 
                        <a href="{% url 'goods:empty' %}" type="button" class="btn btn-outline-warning waves-effect btnCategory">All</a>
                    </li>
                {% for category in categories %}
                
                <li class="list-group-item categoryli"> 
                    <a href="{% url 'goods:categories' category.pk %}" type="button" class="btn btn-outline-warning waves-effect btnCategory">{{category.name}}</a>
                </li>
                
    {% endfor %} 
    </ul>
</div>

templates/footer.html
<!-- FOOOOOOTER -->


  <div class="row" id="footer" >
      <div class="col-md-2"></div>
      <div class="col-md-3 foot">
          <h6>About Us</h6>
          <br>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum perferendis ad laudantium reiciendis ut, consequatur possimus mollitia rerum excepturi quisquam aperiam unde necessitatibus sunt atque maiores ipsum tempore quas esse.
          </p>
      </div>
      <div class="col-md-1"></div>
      <div class="col-md-3 foot">
          <a href="#">Home</a><br>
          <a href="#">About</a><br>
          <a href="#">Store</a><br>
          <a href="#">Contact</a>
      </div>
      <div class="col-md-3  endicon">
          <a class="logo-social" href="#">
              <i class="fa fa-facebook-f"></i>
          </a>
          <a class="logo-social" href="#">
                  <i class="fa fa-instagram"></i>
          </a>
          <a class="logo-social" href="#">
              <i class="fa fa-twitter"></i>
          </a>
      </div>
  </div>

  <div class="row" id="footer2">
      <div class="col-md-3"></div>
      <div class="col-md-6 foot">
          <p id="p4">
              Copyright ©2019 All rights reserved
          </p>
      </div>
      <div class="col-md-3"></div>
  </div>

templates/header.html
<div class="container-fluid">
		<div class="row" id="header">
			<!-- header logo -->
				<div class="col-md-2 header-logo"></div>
				<!-- space-->
				<!-- header searchbox -->
				<div class="col-lg-5 col-md-12 col-sm-12 header-searchbox">
					<!-- Search form -->
					<form method="get" action="../" class="form-inline active-cyan-4" id="search-form">
					  <input required name='word' class="form-control form-control-sm mr-3 w-75" id="search-input" type="text" placeholder="Search"
					    aria-label="Search">
						<input type="submit" value="axtar">
					  <!-- <i class="fas fa-search" type='submit' aria-hidden="true"></i> -->
					</form>
				</div>
				<!-- header menu -->
				<div class="header-menu">
					<ul id="menu-ul">
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                        <li><a href="{% url 'goods:upload' %}">Upload</a></li>
                        
                    {% else %}
                       <li> <a href="{% url 'accounts:login' %}">Login</a></li>
                        <li><a href="{% url 'accounts:register' %}">Register</a></li>
                    {% endif %}
						<li><a class="{% if request.resolver_match.url_name == 'categories' or request.resolver_match.url_name == 'empty'  %}selected{% endif %}" href="{% url 'goods:empty' %}">Categories</a></li>
						<li><a href="">Home</a></li>
					</ul>
				</div>


			</div>
		</div>
	</div>

templates/navbar.html
 <!--/.Navbar-->
<div class="row p-0 m-0" >
<!--/.Navbar-->
        <div class="col-md-12 p-0 m-0">
            <nav class="navbar navbar-expand-lg  navbar-light bg-light">
                <a class="navbar-brand" href="{% url 'goods:goods' %}">MADE WITH LOVE</a>
                <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarsExample08" aria-controls="navbarsExample08" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-center" id="navbarsExample08">
                <ul class="navbar-nav mainnav">
                    <li class="nav-item {% if request.resolver_match.url_name == 'goods' %} active{% endif %}">
                        <a class="nav-link" href="{% url 'goods:goods' %}">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item {% if request.resolver_match.url_name == 'about' %} active{% endif %}">
                        <a class="nav-link" href="{% url 'goods:about' %}">About</a>
                        </li>
                        <li class="nav-item {% if request.resolver_match.url_name == 'empty' %} active{% endif %}">
                        <a class="nav-link" href="{% url 'goods:empty' %}">Store</a>
                        </li>
                        <li class="nav-item {% if request.resolver_match.url_name == 'contact'%} active{% endif %}">
                        <a class="nav-link " href="{% url 'goods:contact' %}" >Contact</a>
                        </li>
                        {% if user.is_authenticated %}       
                        <li class="nav-item">
                            <a class="nav-link " href="{% url 'users:logout' %}" >Logout</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link " >{{user.username}}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " href="{% url 'users:profile' %}" >My profile</a>
                        </li>  
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link " data-toggle="modal" data-target=".bd-example-modal-lg" href="#">Sign up</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id='login_popup' data-toggle="modal" data-target="#exampleModalCenter" href="#">Log in</a>
                    </li>
                   
                    {% endif %}
                </ul>
                </div>
            </nav>
        </div>
    </div>
                <!-- login popup -->
                <!-- Button trigger modal -->
      <!-- Modal login-->
      <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <form class="modal-content" action="{% url 'users:login' %}" id='loginForm' method="POST">
                {% csrf_token %}
                    <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">LOGIN</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    </div>
                    <div class="modal-body">             
                        <div class="row justify-content-center loginpopup">
                            <div class="col-md-10 login  text-center">
                            <input class="inputlogin" name='username' type="text" placeholder="Username">
                            <input class="inputlogin" name='password' type="password" placeholder="Password">
                            <a href="" class="forget">Forgotten password</a>
                            <div class="alert alert-danger" role="alert" id="LoginInfo">
                            
                            </div>
                            <button  class="btn  btn-block logbtn"> Login </button>
                            </div>
                        </div>


                    </div>
                </div>
            </form>
        </div>
      </div>
        <!-- modal login end  -->
   
        <!-- Signup modal -->

    <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Sign up</h5>
                    <button type="button" id='close_icon_signup' class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row justify-content-center loginpopup">
                        <div class="col-md-10 login  text-center">
                            <form class="modal-content" action="{% url 'users:register' %}" id='signUpForm' method="POST">
                                    {% csrf_token %}
                                <table class="table" id="register_table">
                                    <tr>
                                        <td><input class="inputlogin" name='name' type="text" placeholder="Name"></td>
                                        <td><input class="inputlogin" name='surname' type="text" placeholder="Surname"></td>
                                    </tr>
                                    <tr>
                                        <td><input class="inputlogin" name='email' type="email" placeholder="Email"></td>
                                        <td> 
                                            <input class="inputlogin" name='username' type="text" placeholder="Username">
                                        </td>
                                        </tr>
                                    <tr>
                                        <td> <input class="inputlogin" name='password' type="password" placeholder="Password"></td>
                                        <td><input class="inputlogin" name='password2' type="password" placeholder="Confirm Password"></td>
                                    </tr>
                                    <tr>
                                        <td><input class="inputlogin" name='address' type="text" placeholder="Address"></td>
                                        <td><input class="inputlogin" name='phone' type="text" placeholder="Phone number"></td>
                                    </tr>
                                
                                    <tr>
                                        <td  colspan='2'> 
                                            <div class="form-check">
                                                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                                                <label class="form-check-label" for="exampleCheck1">Bütün şərtlərlə razıyam</label>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <!-- <td></td> -->
                                        <td colspan='2'>
                                            <button type="submit" id="savesubmitbtn" disabled=False  class="btn  logbtn"> Sign up </button>
                                        </td>
                                    </tr>
                                </table>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Signup modal end-->